/*
 * Copyright 2023 Santos Zatarain Vera
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package mx.com.inftel.codegen.model

sealed class CodegenType {

    sealed class Id(val autoGenerated: Boolean) : CodegenType() {

        class Integer(autoGenerated: Boolean) : Id(autoGenerated)
        class Long(autoGenerated: Boolean) : Id(autoGenerated)
        class UUID(autoGenerated: Boolean) : Id(autoGenerated)

    }

    sealed class Version : CodegenType() {

        object Integer : Version()
        object Long : Version()

    }

    sealed class Basic : CodegenType() {

        object Integer : Basic()
        object Long : Basic()
        object Boolean : Basic()
        class String(val length: Int? = null) : Basic()
        class BigDecimal(val precision: Int? = null, val scale: Int? = null) : Basic()
        object ByteArray : Basic()
        object UUID : Basic()
        object LocalDateTime : Basic()
        object ZonedDateTime : Basic()

    }

    sealed class OwningSide : CodegenType() {

        class ManyToOne(val target: String) : OwningSide()
    }
}